version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"  # Mapeamento da porta do contêiner WordPress para a porta 8080 do host
    volumes:
      - ./wp-content:/var/www/html/wp-content  # Volume para persistir os dados do WordPress
    environment:
      WORDPRESS_DB_HOST: 'localhost'  # Configuração do banco de dados, mesmo sem um banco separado
      WORDPRESS_DB_USER: 'root'       # Configuração do usuário do banco de dados
      WORDPRESS_DB_PASSWORD: 'root'   # Configuração da senha do banco de dados
      WORDPRESS_DB_NAME: 'wordpress'  # Nome do banco de dados
    restart: always
    networks:
      - mynetwork  # Nome da rede para o contêiner

networks:
  mynetwork:  # Definição de uma rede personalizada
    driver: bridge  # Driver da rede
