version: '3.9'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '1'
          memory: 1G
    env_file:
      - .env  # Lê variáveis do arquivo .env

  redis:
    image: redis:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '0.3'
          memory: 300M
    env_file:
      - .env  # Lê variáveis do arquivo .env

  wordpress:
    image: wordpress:latest
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: ingress
    deploy:
      mode: global
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
    env_file:
      - .env  # Lê variáveis do arquivo .env
    environment:
      # Restante das variáveis de ambiente necessárias para o WordPress...
      TZ: "America/Sao_Paulo"
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-false}
      WP_REDIS_HOST: redis
      WP_REDIS_PORT: 6379
      WP_CACHE: "true"

  wp-cli:
    image: wordpress:cli
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
    env_file:
      - .env  # Lê variáveis do arquivo .env
    environment:
      WP_CLI_CACHE_DIR: ${WP_CLI_CACHE_DIR}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}

  varnish:
    image: varnish:latest
    ports:
      - target: 80
        published: 8000
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
    env_file:
      - .env  # Lê variáveis do arquivo .env

  newrelic:
    image: newrelic/infrastructure:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '0.2'
          memory: 200M
    env_file:
      - .env  # Lê variáveis do arquivo .env

volumes:
  db_data:

networks:
  wordpress-network:
    driver: overlay
