version: '3.7'

networks:
  api:
    driver: overlay
    attachable: true

  monit:
    driver: overlay
    attachable: true

services:
  db:
    image: matheuslfavaretto/db:latest
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: secretpassword
    networks:
      - api
      - monit
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
          memory: 1G

  wordpress:
    depends_on:
      - db
    image: matheuslfavaretto/wordpress:latest
    ports:
      - 8080:80
    networks:
      - api
      - monit
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: secretpassword
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: _wp
    volumes:
      - wordpress_data:/var/www/html
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
          memory: 1G

volumes:
  db_data:
    driver: local
  wordpress_data:
    driver: local
