version: '3.7'

networks:
  frontend:
    driver: overlay
    attachable: true
  backend:
    driver: overlay
    attachable: true

services:
  db:
    image: matheuslfavaretto/db:latest
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: secretpassword
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
          memory: 1G
    logging:
      driver: local
      options:
        max-size: '500m'
        max-file: '5'

  wordpress:
    image: matheuslfavaretto/wordpress:latest
    ports:
      - "8080:80"
    networks:
      - frontend
      - backend
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: secretpassword
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: _wp
      WP_REDIS_HOST: redis
      WP_REDIS_PORT: 6379
      WP_CACHE: "true"
    volumes:
      - wordpress_data:/var/www/html
      - ./wordpress/init_wordpress.sh:/usr/local/bin/init_wordpress.sh
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
          memory: 1G
    logging:
      driver: local
      options:
        max-size: '500m'
        max-file: '5'

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend
    volumes:
      - redis_data:/data
    logging:
      driver: local
      options:
        max-size: '500m'
        max-file: '5'

volumes:
  db_data:
    driver: local
  wordpress_data:
    driver: local
  redis_data:
    driver: local
