version: "3.9"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      NRIA_LICENSE_KEY: "e2b9d1687c93a7dd21e14bfb7b78601aFFFFNRAL"
    networks:
      - wordpress-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - wordpress-network
    environment:
      NRIA_LICENSE_KEY: "e2b9d1687c93a7dd21e14bfb7b78601aFFFFNRAL"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    ports:
      - ${WORDPRESS_PORT}:80
    restart: always
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-false}
      WP_REDIS_HOST: redis
      WP_REDIS_PORT: 6379
      WP_CACHE: "true"
      NRIA_LICENSE_KEY: "e2b9d1687c93a7dd21e14bfb7b78601aFFFFNRAL"
    volumes:
      - ./wp_data:/var/www/html:rw
      - ./configuration/apache2.conf:/etc/apache2/apache2.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - wordpress-network

  wp-cli:
    depends_on:
      - mysql
      - wordpress
    image: wordpress:cli
    env_file: .env
    user: xfs
    environment:
      WP_CLI_CACHE_DIR: ${WP_CLI_CACHE_DIR}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      NRIA_LICENSE_KEY: "e2b9d1687c93a7dd21e14bfb7b78601aFFFFNRAL"
    volumes:
      - ./wp_data:/var/www/html:rw
      - ./bin/install-wp.sh:/usr/local/bin/install-wp:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - wordpress-network

  varnish:
    image: varnish:latest
    ports:
      - "8000:80"
    depends_on:
      - wordpress
    networks:
      - wordpress-network
    command: >
      varnishd -F -a :80 -b wordpress:80 -s malloc,256m
    environment:
      VARNISH_STORAGE: malloc
      VARNISH_STORAGE_SIZE: 256M
      VARNISH_BACKEND_HOST: wordpress
      VARNISH_BACKEND_PORT: 80
      NRIA_LICENSE_KEY: "e2b9d1687c93a7dd21e14bfb7b78601aFFFFNRAL"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  newrelic:
    image: newrelic/infrastructure:latest
    hostname: newrelic
    privileged: true
    environment:
      NRIA_LICENSE_KEY: "e2b9d1687c93a7dd21e14bfb7b78601aFFFFNRAL"
    networks:
      - wordpress-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

volumes:
  db_data:
  wp_data:

networks:
  wordpress-network:
    driver: bridge
