# Use a imagem oficial do MariaDB
FROM mariadb:latest


# Defina as variáveis de ambiente
ENV MYSQL_ROOT_PASSWORD=secretpassword
ENV MYSQL_DATABASE=wordpress
ENV MYSQL_USER=wordpressuser
ENV MYSQL_PASSWORD=secretpassword

# Pode incluir outras configurações necessárias para o seu projeto
